return {
    ["en"] = {
        NativeName = "English",
        EnglishName = "English",
    },
    
    ["cz"] = {
        NativeName = "Čeština",
        EnglishName = "Czech",
    },
    
    ["fr"] = {
        NativeName = "Français",
        EnglishName = "French",
    },
    
    ["de"] = {
        NativeName = "Deutsch",
        EnglishName = "German",
    },
    
    ["pt"] = {
        NativeName = "Português",
        EnglishName = "Portuguese",
    },
    
    ["zh"] = {
        NativeName = "简体中文",
        EnglishName = "Chinese Simplified",
    },
    
    ["ru"] = {
        NativeName = "Русский",
        EnglishName = "Russian",
    }
}
